name: metapi
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - setuptools
  - pandas
  - ruamel.yaml
  - snakemake >=5.10
  - numpy
  - pandas
  - openpyxl
  - biopython>=1.73
  - ruamel.yaml
  - snakemake >=5.10
  - insilicoseq
  - fastqc
  - seqtk
  - seqkit
  - multiqc
  - pigz
  - fastp
  - sickle-trim
  - bwa
  - bowtie2
  - samtools
  - megahit
  - idba
  - spades
  - quast
  - metabat2
  - maxbin2
  - vsearch
  - prodigal
  - prokka
  - checkm-genome
  - drep
  - kraken
  - gtdbtk
